---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
df22 <- read_csv('../data/09-22-2020.csv')
df23 <- read_csv('../data/09-23-2020.csv')
df24 <- read_csv('../data/09-24-2020.csv')
df25 <- read_csv('../data/09-25-2020.csv')
df26 <- read_csv('../data/09-26-2020.csv')
df27 <- read_csv('../data/09-27-2020.csv')
df28 <- read_csv('../data/09-28-2020.csv')

```

```{r}
df22 <- df22 %>%
  filter(Country_Region == 'US') %>%
  filter(Province_State %in% c('New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia'))%>%
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))

df23 <- df23 %>%
  filter(Country_Region == 'US') %>%
  filter(Province_State %in% c('New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia'))%>%
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))

df24 <- df24 %>%
  filter(Country_Region == 'US') %>%
  filter(Province_State %in% c('New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia'))%>%
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))

df25 <- df25 %>%
  filter(Country_Region == 'US') %>%
  filter(Province_State %in% c('New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia'))%>%
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))

df26 <- df26 %>%
  filter(Country_Region == 'US') %>%
  filter(Province_State %in% c('New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia'))%>%
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))

df27 <- df27 %>%
  filter(Country_Region == 'US') %>%
  filter(Province_State %in% c('New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia'))%>%
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))

df28 <- df28 %>%
  filter(Country_Region == 'US') %>%
  filter(Province_State %in% c('New York','New Jersey','Massachusetts','Virginia','Maryland','Pennsylvania','Connecticut','Delaware','Rhode Island','Washington DC','West Virginia'))%>%
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))

```


```{r}
df_w4 <- rbind(df22, df23, df24, df25, df26, df27, df28)
df_w4 <- df_w4 %>% 
  mutate(Last_Update = as.POSIXct(Last_Update)) %>%
  mutate(Last_Update = Last_Update - days(1)) %>%
  mutate(Last_Update = format(Last_Update, '%Y-%m-%d'))
```

```{r}
df_w4
write_csv(df_w4, '../output/week4.csv')
```

